// Shared types and utilities for the Legal Document AI Assistant

// Export types (interfaces)
export * from './types';

// Export schemas and their inferred types with different names to avoid conflicts
export {
  TextLocationSchema,
  DocumentMetadataSchema,
  KeyTermSchema,
  RiskSchema,
  ClauseSchema,
  DocumentAnalysisSchema,
  DocumentSchema,
  UserPreferencesSchema,
  UserProfileSchema,
  UserSubscriptionSchema,
  UserSchema,
  DocumentUploadSchema,
  DocumentAnalysisRequestSchema,
  QuestionSchema,
  UserRegistrationSchema,
  UserUpdateSchema,
  // Template schemas
  CustomizationOptionSchema,
  TemplateAnnotationSchema,
  ClauseAlternativeSchema,
  StandardClauseSchema,
  DocumentTemplateSchema,
  MissingClauseSchema,
  TemplateDeviationSchema,
  TemplateComparisonSchema,
  TemplateSearchSchema,
  TemplateCustomizationSchema,
  TemplateComparisonRequestSchema,
  // Business feature schemas
  WorkspaceSettingsSchema,
  WorkspaceSchema,
  WorkspacePermissionsSchema,
  WorkspaceMemberSchema,
  SharePermissionsSchema,
  DocumentShareSchema,
  BulkDocumentSchema,
  BulkProcessingSettingsSchema,
  BulkDocumentResultSchema,
  BulkProcessingResultsSchema,
  BulkProcessingJobSchema,
  WorkspaceInvitationSchema,
  WorkspaceActivitySchema,
  CreateWorkspaceSchema,
  UpdateWorkspaceSchema,
  InviteMemberSchema,
  ShareDocumentSchema,
  CreateBulkJobSchema,
} from './schemas';

// Export inferred types with Schema suffix to avoid conflicts
export type {
  TextLocation as TextLocationSchemaType,
  DocumentMetadata as DocumentMetadataSchemaType,
  KeyTerm as KeyTermSchemaType,
  Risk as RiskSchemaType,
  Clause as ClauseSchemaType,
  DocumentAnalysis as DocumentAnalysisSchemaType,
  Document as DocumentSchemaType,
  UserPreferences as UserPreferencesSchemaType,
  UserProfile as UserProfileSchemaType,
  UserSubscription as UserSubscriptionSchemaType,
  User as UserSchemaType,
  DocumentUpload,
  DocumentAnalysisRequest,
  Question,
  UserRegistration,
  UserUpdate,
  // Template types
  CustomizationOption,
  TemplateAnnotation,
  ClauseAlternative,
  StandardClause,
  DocumentTemplate as DocumentTemplateSchemaType,
  MissingClause,
  TemplateDeviation,
  TemplateComparison as TemplateComparisonSchemaType,
  TemplateSearch,
  TemplateCustomization,
  TemplateComparisonRequest,
  // Business feature types
  WorkspaceSettings,
  Workspace as WorkspaceSchemaType,
  WorkspacePermissions,
  WorkspaceMember as WorkspaceMemberSchemaType,
  SharePermissions,
  DocumentShare as DocumentShareSchemaType,
  BulkDocument as BulkDocumentSchemaType,
  BulkProcessingSettings,
  BulkDocumentResult,
  BulkProcessingResults,
  BulkProcessingJob as BulkProcessingJobSchemaType,
  WorkspaceInvitation as WorkspaceInvitationSchemaType,
  WorkspaceActivity as WorkspaceActivitySchemaType,
  CreateWorkspace,
  UpdateWorkspace,
  InviteMember,
  ShareDocument,
  CreateBulkJob,
} from './schemas';

export * from './utils';
export * from './migrations';